version: '3.8'

services:
  app:
    container_name: webtrade
    build:
      context: ..
      dockerfile: .prodcontainer/dockerfile

    networks:
      - renet

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443

    networks:
      - renet

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.logs:/var/log/nginx
      - ./letsencrypt:/var/www/letsencrypt
      - ./ssl:/etc/ssl/nginx
      - ./.htpasswd:/etc/nginx/.htpasswd

volumes:
  mongodb-data:


networks:
  renet:
    driver: bridge
